language: go

go:
    - 1.5.1
    - tip

before_install:
    - go get -t github.com/avadhutp/phileas
    - go get github.com/onsi/gomega
    - go get github.com/onsi/ginkgo
    - go get golang.org/x/tools/cmd/cover

script: 
    - make lint